### ISSUE TITLE
Unable to Detect Shake Events on Android Devices

### ISSUE THREAD

**Issue by alex-ami** [Cap-go/capacitor-shake#52]
**Issue Description**
I'm encountering difficulties in detecting shake events within my Android application utilizing the Cap-go / capacitor-shake plugin. Despite implementing the shake listener and adding logs for verification, no console outputs or indications of shake detection are observed.

**To Reproduce**
1. Implement the shake listener within an Android application using the Cap-go / capacitor-shake plugin.
2. Add logging mechanisms to confirm the invocation of the shake listener.
3. Test the application on an Android device by performing shake gestures.

**Expected behavior**
Upon shaking the device, the shake listener should be invoked, and corresponding logs indicating the detection of the shake event should be displayed in the console.

**Actual Behavior**
Despite shaking the device, the shake listener does not seem to be triggered, and no logs regarding shake events are observed in the console.

**Environment**
 - Device: SAMSUNG GALAXY M34 5G 
 - OS: Android 14
 - Cap-go Version: ^5.0.29

**Additional Information**
I have thoroughly reviewed my implementation and ensured that all necessary configurations and permissions are correctly set up. However, I am still unable to detect shake events reliably. Any guidance or insights regarding this issue would be greatly appreciated.

**Comment by nomadminded** [comment]
I replicate this issue.

**Comment by WcaleNieWolny** [comment]
I am sorry, but there was no implementation for Android.

I implemented android in [this commit](https://github.com/Cap-go/capacitor-shake/commit/db63a57fd59ff446d4aa2d84cc2066a03fd38f06)

Here is a demo:


https://github.com/user-attachments/assets/761e052c-bb05-4ab3-9216-a9f363cd46de
